export const CONFIG = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,

  // Colors
  COLOR_BG: '#000000',
  COLOR_PLAYER: '#00f0ff',
  COLOR_ENEMY: '#ff007a',
  COLOR_DIVER: '#ff4444',
  COLOR_BULLET: '#ffffff',
  COLOR_HUD: '#00f0ff',
  COLOR_BANNER: '#ffd700',
  COLOR_JONAS: '#ffd700',
  COLOR_STAR_DIM: 'rgba(255,255,255,0.25)',
  COLOR_STAR_MID: 'rgba(255,255,255,0.6)',
  COLOR_STAR_BRIGHT: 'rgba(255,255,255,1.0)',

  // Player
  PLAYER_SPEED: 320,
  PLAYER_WIDTH: 32,
  PLAYER_HEIGHT: 36,
  PLAYER_HITBOX_SCALE: 0.7,
  PLAYER_GLOW: 14,
  PLAYER_START_Y_OFFSET: 60,

  // Bullet
  BULLET_SPEED: 520,
  BULLET_WIDTH: 3,
  BULLET_HEIGHT: 14,
  BULLET_GLOW: 8,

  // Enemies
  ENEMY_COLS: 8,
  ENEMY_ROWS: 4,
  ENEMY_SPACING_X: 72,
  ENEMY_SPACING_Y: 56,
  ENEMY_TOP_MARGIN: 80,
  ENEMY_SIZE: 20,
  ENEMY_HITBOX: 18,
  ENEMY_GLOW: 10,
  ENEMY_SWAY_BASE: 55,
  ENEMY_SWAY_INCREMENT: 7,
  ENEMY_EDGE_PADDING: 40,

  // Dive-bombing
  DIVE_INTERVAL: 3.5,
  DIVE_INTERVAL_VARIANCE: 1.0,
  DIVE_MAX_SIMULTANEOUS: 2,
  DIVE_ACCEL: 180,
  DIVE_MAX_SPEED: 380,
  DIVE_MAX_VX: 200,
  DIVE_LOOP_Y: 530,        // y threshold to start loop-back (must be past player hitbox ~527)
  DIVE_STEER: 1.5,
  DIVE_WOBBLE_AMP: 18,
  DIVE_WOBBLE_SPEED: 5.0,
  LOOP_ACCEL: 600,
  RETURN_SPEED: 260,
  RETURN_SNAP_DIST: 20,

  // Score / lives
  SCORE_PER_ENEMY: 100,
  SCORE_NAT20_BONUS: 2000,
  STARTING_LIVES: 3,

  // Enemy bullets
  COLOR_ENEMY_BULLET: '#ff7700',
  ENEMY_BULLET_WIDTH: 4,
  ENEMY_BULLET_HEIGHT: 12,
  ENEMY_BULLET_GLOW: 8,

  // Beholder boss
  COLOR_BEHOLDER:       '#cc44ff',
  COLOR_BEHOLDER_EYE:   '#ff44ff',
  BEHOLDER_RADIUS:       70,
  BEHOLDER_EYE_RADIUS:   12,
  BEHOLDER_STALK_LENGTH: 30,
  BEHOLDER_DESCENT_SPEED: 30,
  BEHOLDER_REST_Y:       130,
  BEHOLDER_SCORE_PER_EYE: 500,

  // Critical hits (normal mode only)
  COLOR_CRIT: '#ffffff',
  CRIT_CHANCE: 0.05,
  CRIT_RADIUS: 90,
  CRIT_SCORE: 300,
  CRIT_PARTICLE_COUNT: 32,

  // Wave banner
  WAVE_BANNER_DURATION: 2200,

  // Seal waves
  SEAL_BANNER_DURATION:   4500, // ms — longer than normal banner to read 2 lines
  DECOY_FLASH_DURATION:   0.25, // seconds — white flash on decoy hit
  SEAL_DEEP_RESPAWN_DELAY: 18,  // seconds before a killed enemy revives

  // Particles
  PARTICLE_COUNT: 14,
  PARTICLE_SPEED_MIN: 60,
  PARTICLE_SPEED_MAX: 210,
  PARTICLE_LIFETIME_MIN: 0.4,
  PARTICLE_LIFETIME_MAX: 0.9,
  PARTICLE_SIZE: 3,

  // Starfield
  STAR_COUNT_DIM: 70,
  STAR_COUNT_MID: 50,
  STAR_COUNT_BRIGHT: 30,
  STAR_SPEED_DIM: 20,
  STAR_SPEED_MID: 55,
  STAR_SPEED_BRIGHT: 110,

  // Loop
  FIXED_STEP: 1 / 60,
  MAX_STEPS: 5,
};
